modLoader = "javafml"
loaderVersion = "[46,)"
license = "All rights reserved"

[[mods]]
    modId = "recipebook_api"
    version = "${version}"
    displayName = "RecipeBookAPI"
    #updateJSONURL="https://change.me.example.invalid/updates.json"
    displayURL="https://curseforge.com/minecraft/mc-mods/recipebook-api"
    issueTrackerURL="https://github.com/MincraftEinstein/RecipeBookAPI/issues"
    logoFile = "pack.png"
    authors = "MincraftEinstein"
    description = '''
Provides a simple to use API to create recipe book support for custom processing/crafting blocks
'''

[[dependencies.recipebook_api]]
    modId = "forge"
    mandatory = true
    versionRange = "[46,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.recipebook_api]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.2,1.21)"
    ordering = "NONE"
    side = "BOTH"
